language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: vp12FDo5Ow3plVQc4RJ7hwLV8mwRSZFAAtq9lod0dBYL+LoVzW4gpgMVSzvf/z2yn/MQajKluVgnB3QJ1yeuEGlxVRtQyMteYs+fupwm0HAo7CNSxrFq3ezY0zG8nG4smOpnl1uqmlXHdHfgwKyD8w52kr0paQ14stT6sZOnP4Y0kE1aWq+dNuE1oB3sSCU8CCKPMTOdrucRlktfDxer2qUSrhYfVNYRMIG38VySD6K6AlMafi+0QzmYp+qWQIlORvTcEn0O4bofBkRC56BqJuYxXbohLeJ6lSx/GblIO659iWZDfVxGQvig7/WXlSbJdx833bgVKcyPmDRvbgPNvr8hoZMa3gZiZFI4maL1oCJZ6K5BIXKWFiaCLigpDjUFYPiA4Ml+ptqYSxRmm28+rWpD3Mqnf32T3yDMU8Pg5oTkLDtFTV1qboiHo5PSgFShTls5HAkVmhmcO8VvYKDD+qPEWalPfCLl1M+NUWdhZUWGtzv8WGl8pE2QfGR9c5w+IL/NNBFbug+0Lsr6VJgNA0buhRTlOqxpAGDSIu0QIks6tlrqnJNizkSQEWxk1c8pvlBjK9DHWXIKS30/KWICexhPLecQnM3Cx2hvQC98JiFc2rrnoZnQXD+6dpMARCIc4uJB9C1+RQaKMAFKUqSs5x9uud8VbhvWoYxSaWh0Q2Q=
  app: stormy-journey-12636
